<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	  <RootNamespace>SFA.DAS.TestDataCleanup</RootNamespace>
	  <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.6.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		
		
		<PackageReference Include="SpecFlow.Tools.MsBuild.Generation" Version="3.9.74" />
		<PackageReference Include="SpecFlow.NUnit" Version="3.9.74" />
	</ItemGroup>

	<ItemGroup>
		<Compile Include="..\NUnitConfigurator.cs" Link="NUnitConfigurator.cs" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SFA.DAS.ConfigurationBuilder\SFA.DAS.ConfigurationBuilder.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="appsettings.Environment.json">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		  <CopyToPublishDirectory>Never</CopyToPublishDirectory>
	  </None>
	  <None Update="Project\Helpers\SqlScripts\EasAccTestDataCleanUp.sql">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	  <None Update="Project\Helpers\SqlScripts\EasComtTestDataCleanUp.sql">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	  <None Update="Project\Helpers\SqlScripts\EasFcastTestDataCleanUp.sql">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	  <None Update="Project\Helpers\SqlScripts\EasFinTestDataCleanUp.sql">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	  <None Update="Project\Helpers\SqlScripts\EasAppfbTestDataCleanUp.sql">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	  <None Update="Project\Helpers\SqlScripts\EasPfbeTestDataCleanUp.sql">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	  <None Update="Project\Helpers\SqlScripts\EasPsrTestDataCleanUp.sql">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	  <None Update="Project\Helpers\SqlScripts\EasRsrvTestDataCleanUp.sql">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	  <None Update="Project\Helpers\SqlScripts\EasUsersTestDataCleanUp.sql">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	  <None Update="Project\Helpers\SqlScripts\EasPrelTestDataCleanUp.sql">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	  <None Update="Project\Helpers\SqlScripts\EasAComtTestDataCleanUp.sql">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	  <None Update="Project\Helpers\SqlScripts\EasLtmTestDataCleanUp.sql">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	  <None Update="Project\Helpers\SqlScripts\EmpIncTestDataCleanUp.sql">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	  <None Update="specflow.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>
