<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
      <PackageId>SFA.DAS.UI.FrameworkHelpers</PackageId>
	  <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
      <Title>Specflow DotNet Core UI framework helpers</Title>
      <Configurations>Debug;Release;Development</Configurations>
      <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
      <PackageVersion>1.0.2</PackageVersion>
      <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
      <Authors>arvinthseran; Imran Ali</Authors>
      <Company>SFA.DAS</Company>
      <Description>A generic helpers wrapper for Specflow UI Framework integrated with donet core</Description>
      <PackageProjectUrl>https://accounts.manage-apprenticeships.service.gov.uk/service/index</PackageProjectUrl>
      <RepositoryUrl>https://github.com/SkillsFundingAgency/DFE-Standardised-Test-Automation-Framework/tree/master/src/SFA.DAS.UI.FrameworkHelpers</RepositoryUrl>
	  <PackageLicenseExpression>MS-PL</PackageLicenseExpression>
      <NeutralLanguage>en</NeutralLanguage>
      <PackageTags>cosmosdb webdriver</PackageTags>
      <RepositoryType>git</RepositoryType>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SFA.DAS.FrameworkHelpers\SFA.DAS.FrameworkHelpers.csproj" />
		<ProjectReference Include="..\SFA.DAS.TestDataExport\SFA.DAS.TestDataExport.csproj" />
	</ItemGroup>

  <ItemGroup>
	<PackageReference Include="RestSharp" Version="112.1.0" />
    <PackageReference Include="DotNetSeleniumExtras.WaitHelpers" Version="3.11.0" />
    <PackageReference Include="Selenium.Axe" Version="4.0.*" />
    <PackageReference Include="Selenium.Support" Version="4.36.0" />
    <PackageReference Include="Selenium.WebDriver" Version="4.36.0" />
	<PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="141.0.7390.7600" />
  </ItemGroup>

  <ItemGroup>
    <None Update="html2canvas.js">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
