<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFramework>net8.0</TargetFramework>
	  <RootNamespace>SFA.DAS.EmployerFinance.APITests</RootNamespace>
	  <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
	  <IsPackable>false</IsPackable>
  </PropertyGroup>

	<ItemGroup>
		<Compile Include="..\NUnitConfigurator.cs" Link="NUnitConfigurator.cs">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SFA.DAS.API.Framework\SFA.DAS.API.Framework.csproj" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
    
    
    <PackageReference Include="SpecFlow.NUnit" Version="3.9.74" />
    <PackageReference Include="SpecFlow.Tools.MsBuild.Generation" Version="3.9.74" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.Environment.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
    <None Update="appsettings.Project.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="specflow.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
