<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>SFA.DAS.EarlyConnectForms.UITests</RootNamespace>
		<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
		<IsPackable>false</IsPackable>
	</PropertyGroup>
	
	<ItemGroup>
		<Compile Include="..\NUnitConfigurator.cs" Link="NUnitConfigurator.cs">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Compile>
	</ItemGroup>
	
	
  <ItemGroup>
	  
	  <PackageReference Include="Mailosaur" Version="8.9.0" />
	  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0">
	  <PrivateAssets>all</PrivateAssets>
	  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
    
      
	<PackageReference Include="SpecFlow.Tools.MsBuild.Generation" Version="3.9.74" />
	<PackageReference Include="SpecFlow.NUnit" Version="3.9.74" />
	<PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SFA.DAS.MailosaurAPI.Service\SFA.DAS.MailosaurAPI.Service.csproj" />
		<ProjectReference Include="..\SFA.DAS.TestDataExport\SFA.DAS.TestDataExport.csproj" />
		<ProjectReference Include="..\SFA.DAS.ConfigurationBuilder\SFA.DAS.ConfigurationBuilder.csproj" />
		<ProjectReference Include="..\SFA.DAS.UI.Framework\SFA.DAS.UI.Framework.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.Environment.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</None>
		<None Update="appsettings.Project.BrowserStack.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="appsettings.Project.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="specflow.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
