<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	  <RootNamespace>SFA.DAS.Approvals.IntegrationTests</RootNamespace>
	  <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
	  <IsPackable>false</IsPackable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Messaging.ServiceBus" Version="7.18.*" />
		<PackageReference Include="Selenium.Support" Version="4.25.0" />
		<PackageReference Include="Selenium.WebDriver" Version="4.25.0" />
		<PackageReference Include="SFA.DAS.Payments.ProviderPayments.Messages" Version="0.1.187" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.6.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
		<PackageReference Include="SFA.DAS.NServiceBus" Version="17.0.49" />
		<PackageReference Include="SpecFlow.Tools.MsBuild.Generation" Version="3.9.74" />
		<PackageReference Include="SpecFlow.NUnit" Version="3.9.74" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SFA.DAS.TestDataExport\SFA.DAS.TestDataExport.csproj" />
		<ProjectReference Include="..\SFA.DAS.ConfigurationBuilder\SFA.DAS.ConfigurationBuilder.csproj" />
		<ProjectReference Include="..\SFA.DAS.Registration.UITests\SFA.DAS.Registration.UITests.csproj" />
		<ProjectReference Include="..\SFA.DAS.Approvals.UITests\SFA.DAS.Approvals.UITests.csproj" />
		<ProjectReference Include="..\SFA.DAS.ProviderLogin.Service\SFA.DAS.ProviderLogin.Service.csproj" />
		<ProjectReference Include="..\SFA.DAS.UI.Framework\SFA.DAS.UI.Framework.csproj" />
		<ProjectReference Include="..\SFA.DAS.MailosaurAPI.Service\SFA.DAS.MailosaurAPI.Service.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="appsettings.Environment.json">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
		  <CopyToPublishDirectory>Never</CopyToPublishDirectory>
	  </None>
	  <None Update="appsettings.Project.json">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	  <None Update="specflow.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
	
</Project>
