<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	  <RootNamespace>SFA.DAS.API.Framework</RootNamespace>
	  <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    
    
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SFA.DAS.API.FrameworkHelpers\SFA.DAS.API.FrameworkHelpers.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="appsettings.ApiFramework.json">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
