<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>SFA.DAS.MailosaurAPI.Service</RootNamespace>
		<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Mailosaur" Version="8.9.*" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
		
		
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SFA.DAS.API.FrameworkHelpers\SFA.DAS.API.FrameworkHelpers.csproj" />
	</ItemGroup>


</Project>
