# trigger:
#   branches:
#     include:
#       - master

variables:
  - name: BuildConfiguration
    value: release
  - name: BuildPlatform
    value: any cpu
  - group: BUILD Management Resources
  - group: Release Automation Suite Variables
  - group: Release Automation Suite Variables (Db)
  - group: Provider Release Automation Suite Variables
  - group: RELEASE das-accessibility-automation-test-suite
  - group: PreProd Management Resources
  - group: PreProd Shared Resources
  - group: PreProd Automation Suite Variables
  - group: PREPROD das-accessibility-automation-test-suite
  - name: Deploy
    value: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'Manual'), eq(variables['Build.Reason'], 'PullRequest'))]

resources:
  repositories:
    - repository: self
    - repository: das-platform-building-blocks
      type: github
      name: SkillsFundingAgency/das-platform-building-blocks
      ref: refs/tags/3.0.10
      endpoint: SkillsFundingAgency
    - repository: das-platform-automation
      type: github
      name: SkillsFundingAgency/das-platform-automation
      ref: refs/tags/5.1.8
      endpoint: SkillsFundingAgency

stages:
  - stage: Build
    jobs:
      - job: CodeBuild
        pool:
          name: DAS - Continuous Integration Agents
        workspace:
          clean: all
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'dotnet build'
            inputs:
              projects: 'src/**/*.csproj'
              arguments: '--configuration $(BuildConfiguration)'

          - task: CopyFiles@2
            displayName: 'Copy plain files to: $(build.artifactstagingdirectory)/src'
            inputs:
              Contents: |
                src/**/*.sql
                src/**/html2canvas.js
                src/**/appsettings.Config.json
                src/**/appsettings.AdminConfig.json
                src/**/appsettings.ProviderConfig.json
                src/**/appsettings.TimeOutConfig.json
                src/**/appsettings.TestExecution.json
                src/**/appsettings.NServiceBusConfig.json
                src/**/appsettings.BrowserStack.json
                src/**/appsettings.ApiFramework.json
              TargetFolder: '$$(Build.SourcesDirectory)/src/SFA.DAS.Campaigns.UITests/bin/$(BuildConfiguration)/net8.0/files'
              flattenFolders: true
              OverWrite: true

  - stage: Deploy_PP
    dependsOn: Build
    displayName: Deploy to PP
    jobs:
      - deployment: Deploy_AutomationTests
        displayName: 'Deploy Automation Tests to PP'
        pool:
          vmImage: 'windows-latest'
        environment: PP
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  displayName: 'Checkout current branch'

                - checkout: das-platform-automation
                  displayName: 'Checkout das-platform-automation templates'

                - task: browserstackcom.browserstack-vsts-extension.browserstack-config-task.BrowserStackConfig@0
                  displayName: 'BrowserStack - Configuration'
                  inputs:
                    BrowserStackServiceEndPoint: 'AS-Browserstack'

                - script: dir $(System.DefaultWorkingDirectory) /S
                  displayName: 'List ALL contents in System.DefaultWorkingDirectory (recursive)'

                - script: dir $(Build.SourcesDirectory) /S
                  displayName: 'List ALL contents in Build.SourcesDirectory (recursive)'

                - task: PowerShell@2
                  displayName: 'Debug - List All Environment Variables'
                  inputs:
                    targetType: 'inline'
                    script: |
                      Write-Host "--- Listing All Environment Variables ---"
                      Get-ChildItem Env: | Sort-Object Name
                      Write-Host "----------------------------------------"

                - script: |
                    echo "##[section]Working Directory:"
                    cd
                    echo "##[section]Folder Contents:"
                    dir
                  displayName: 'Print working directory and list folders'

                - task: DotNetCoreCLI@2
                  displayName: 'Run ALL Accessibility Tests (Local Agent)'
                  inputs:
                    command: test
                    projects: $(ProjectPath)
                    arguments: '--no-build --configuration $(BuildConfiguration) --filter "TestCategory=$(TestCategory)" --logger "trx;LogFileName=test_results.trx"'
                    testRunTitle: 'Accessibility test $(DATE_TIME)'
                    publishTestResults: false

                - task: browserstackcom.browserstack-vsts-extension.reports-task.BrowserStackResults@1
                  displayName: 'BrowserStack - Results'
